//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBERREP.Controls
{


    public partial class SignUp
    {
        protected global::System.Web.UI.WebControls.TextBox TXTName;
        protected global::System.Web.UI.WebControls.TextBox TXTEmail;
        protected global::System.Web.UI.WebControls.TextBox TXTPassword;
        protected global::System.Web.UI.WebControls.TextBox TXTConfirmPassword;
        protected global::System.Web.UI.WebControls.Button BTNSave;
    }
}
