//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBERREP {
    
    
    public partial class dBoard {
        
        /// <summary>
        /// MyAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UBERREP.Controls.MyAccount MyAccount;
        
        /// <summary>
        /// UsersListSales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UBERREP.Controls.UsersList UsersListSales;
        
        /// <summary>
        /// UsersListRetailer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UBERREP.Controls.UsersList UsersListRetailer;
    }
}
